query GetUserBribeClaims($user: String!) {
  getUserBribeClaims(user: $user) {
    distributionId
    amountOwed
    briber
    gauge
    token
    merkleProof
    valueUSD
    gaugeRecord {
      symbol
    }
    pool {
      name
    }
  }
}

query GetUserGaugeRewards($user: String!) {
  userGetUserPendingGaugeRewards(user: $user) {
    stakingRewards {
      ...UserRewardFragment
    }

    protocolRewards {
      ...UserRewardFragment
    }

    gaugeRewards {
      pool {
        name
        staking {
          gauge {
            gaugeAddress
          }
        }
      }

      rewards {
        amount
        valueUSD

        token {
          address
          symbol
          logoURI
        }
      }
    }
  }
}

fragment UserRewardFragment on GqlBaseTokenReward {
  pool {
    name
    address

    staking {
      gauge {
        gaugeAddress
      }
    }
  }

  isRewardBPT
  amount
  valueUSD

  token {
    address
    symbol
  }

  tokenList {
    address
    logoURI
  }
}
