query GetUserBribeClaims($user: String!) {
  getUserBribeClaims(user: $user) {
    distributionId
    amountOwed
    briber
    gauge
    token
    proof
    valueUSD
    gaugeRecord {
      symbol
    }
    pool {
      name
    }
  }
}

query GetUserGaugeRewards($user: String!) {
  userGetUserPendingGaugeRewards(user: $user) {
    stakingRewards {
      pool {
        name
        address
        allTokens {
          token {
            address
            logoURI
          }
        }
      }
      amount
      valueUSD

      token {
        address
        logoURI
      }
    }

    protocolRewards {
      pool {
        name
      }

      tokenList {
        address
      }
    }
  }
}
