query GetUserBribeClaims($user: String!) {
  getUserBribeClaims(user: $user) {
    distributionId
    amountOwed
    briber
    gauge
    token
    proof
    valueUSD
    gaugeRecord {
      symbol
    }
    pool {
      name
    }
  }
}

query GetUserGaugeRewards($user: String!) {
  userGetUserPendingGaugeRewards(user: $user) {
    stakingRewards {
      ...UserRewardFragment
    }

    protocolRewards {
      ...UserRewardFragment
    }
  }
}

fragment UserRewardFragment on GqlBaseTokenReward {
  pool {
    name
    address
    allTokens {
      token {
        address
        logoURI
      }
    }

    staking {
      gauge {
        gaugeAddress
      }
    }
  }
  amount
  valueUSD
}
