query GetRewardPools($user: String) {
  getRewardPools(user: $user) {
    poolId
    daysRemaining
    amountStaked
    amountStakedValue
    isPartnerPool
    rewardToken {
      address
      name
      symbol
      logoURI
    }

    aprs {
      apr
      daily
    }

    userInfo {
      poolId
      amountDeposited
      amountDepositedFull
      depositValue
      hasPendingRewards
      pendingRewards
      pendingRewardValue
      percentageOwned
    }
  }
}

query GetRewardPoolsData {
  getRewardPoolsData {
    poolId
    daysRemaining
    amountStaked
    amountStakedValue
    isPartnerPool
    rewardToken {
      address
      name
      symbol
      logoURI
    }

    aprs {
      apr
      daily
    }

    userInfo {
      poolId
      amountDeposited
      amountDepositedFull
      depositValue
      hasPendingRewards
      pendingRewards
      pendingRewardValue
      percentageOwned
    }
  }
}
