query GetRewardPools($user: String) {
  getRewardPools(user: $user) {
    poolId
    daysRemaining
    amountStaked
    amountStakedValue
    isPartnerPool
    rewardIsBPT
    poolDisplayTokens {
      address
      weight
      symbol
      logoURI
    }

    rewardToken {
      address
      name
      symbol
      logoURI
    }

    aprs {
      apr
      daily
    }

    userInfo {
      poolId
      amountDeposited
      amountDepositedFull
      depositValue
      hasPendingRewards
      pendingRewards
      pendingRewardValue
      percentageOwned
    }
  }
}
